version: '3'
volumes:
  postgres_data: {}
  elastic_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    environment:
      - MIX_ENV=prod
      - PGPASSWORD=postgres
    tty: true
    depends_on:
      - postgres
      - elasticsearch
      - redis

  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "none"

  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - elastic_data:/var/lib/elasticsearch
    logging:
      driver: "none"
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

  redis:
    image: redis:5.0.9
    logging:
      driver: "none"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - app
    ports:
      - '8080:8080'
